# Generated by Django 5.0.6 on 2026-02-12 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0004_task_end_date_task_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='time_spent',
            field=models.FloatField(default=0.0, help_text='Time spent in hours'),
        ),
    ]
