# Generated by Django 5.1.3 on 2026-02-20 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0008_epic_task_epic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='environment',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='task',
            name='issue_type',
            field=models.CharField(choices=[('TASK', 'Task'), ('STORY', 'Story'), ('BUG', 'Bug')], default='TASK', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='reporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='story_points',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(default='#3B82F6', max_length=7)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='project_management.project')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='project_management.label'),
        ),
    ]
