# Generated by Django 5.1.3 on 2026-02-20 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0012_taskstatus_task_status_obj_workflowtransition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='status_obj',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='project_management.taskstatus'),
        ),
    ]
