# Generated by Django 5.0.6 on 2026-02-25 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0015_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('ASSIGNMENT', 'Assignment'), ('STATUS_CHANGE', 'Status Change'), ('COMMENT', 'Comment'), ('MENTION', 'Mention'), ('SYSTEM', 'System')], default='SYSTEM', max_length=20),
        ),
    ]
