# Generated by Django 5.1.3 on 2026-02-25 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0018_projectmessage_attachment_projectmessage_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmessage',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
    ]
