# Generated by Django 5.1.3 on 2026-02-25 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0019_projectmessage_is_edited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmessage',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
