# Generated by Django 5.1.3 on 2026-02-27 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0021_documentation_documentrevision'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentation',
            options={'ordering': ['order', 'created_at']},
        ),
        migrations.AddField(
            model_name='documentation',
            name='order',
            field=models.IntegerField(default=0, verbose_name='الترتيب'),
        ),
        migrations.AddField(
            model_name='documentation',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='project_management.documentation', verbose_name='التوثيق الأب'),
        ),
    ]
