# Generated by Django 5.0.6 on 2026-03-02 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0022_alter_documentation_options_documentation_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=255, verbose_name='التطبيق (App)')),
                ('path', models.CharField(max_length=500, verbose_name='المسار (Path)')),
                ('method', models.CharField(max_length=10, verbose_name='النوع (Method)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_endpoints', to='project_management.project', verbose_name='المشروع')),
            ],
            options={
                'ordering': ['app_name', 'path', 'method'],
            },
        ),
    ]
