# Generated by Django 5.0.6 on 2026-03-02 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0023_apiendpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiendpoint',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات المطورين'),
        ),
    ]
