# Generated by Django 5.2.12 on 2026-04-08 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0030_add_task_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='committed_points',
            field=models.IntegerField(default=0, help_text='Story points committed at sprint start'),
        ),
        migrations.AddField(
            model_name='sprint',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='When the sprint was completed', null=True),
        ),
        migrations.AddField(
            model_name='sprint',
            name='completed_points',
            field=models.IntegerField(default=0, help_text='Story points completed in this sprint'),
        ),
        migrations.AddField(
            model_name='sprint',
            name='completed_tasks',
            field=models.IntegerField(default=0, help_text='Number of tasks completed'),
        ),
        migrations.AddField(
            model_name='sprint',
            name='total_tasks',
            field=models.IntegerField(default=0, help_text='Total tasks in sprint'),
        ),
    ]
