# Generated by Django 5.2.12 on 2026-04-09 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0032_doc_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(default='#3B82F6', max_length=7)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc_tags', to='project_management.project')),
            ],
            options={
                'unique_together': {('project', 'name')},
            },
        ),
        migrations.AddField(
            model_name='documentation',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='documents', to='project_management.doctag'),
        ),
    ]
