# Generated by Django 5.2.12 on 2026-04-09 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0033_add_doctag_and_doc_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='pluginmodel',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
