# Generated by Django 5.2.12 on 2026-04-15 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0035_task_status_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskstatus',
            name='category',
            field=models.CharField(choices=[('TO_DO', 'To Do'), ('IN_PROGRESS', 'In Progress'), ('PENDING', 'Pending'), ('IN_REVIEW', 'In Review'), ('DONE', 'Done')], default='IN_PROGRESS', max_length=20),
        ),
    ]
