# Generated by Django 5.0.6 on 2026-02-10 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='project_name',
            field=models.CharField(default='General', max_length=100),
            preserve_default=False,
        ),
    ]
