# Generated by Django 5.0.6 on 2026-02-10 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_user_bio_user_job_title_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='project_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='user',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
    ]
