# Generated by Django 5.0.6 on 2026-02-10 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_remove_issue_project_name_remove_user_bio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('can_view_dashboard', models.BooleanField(default=True)),
                ('can_view_issues', models.BooleanField(default=True)),
                ('can_view_users', models.BooleanField(default=True)),
                ('can_view_settings', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='permission_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='tracker.permissiongroup'),
        ),
    ]
