# Generated by Django 5.0.6 on 2026-02-10 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_permissiongroup_user_permission_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissiongroup',
            name='can_delete_issues',
            field=models.BooleanField(default=False),
        ),
    ]
