# Generated by Django 5.1.3 on 2026-02-13 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_issue_resolved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissiongroup',
            name='can_create_project',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permissiongroup',
            name='can_create_task',
            field=models.BooleanField(default=False),
        ),
    ]
