# Generated by Django 5.1.3 on 2026-02-13 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_permissiongroup_can_create_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissiongroup',
            name='can_view_user_projects',
            field=models.BooleanField(default=False),
        ),
    ]
