# Generated by Django 5.0.6 on 2026-03-04 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_permissiongroup_can_view_user_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissiongroup',
            name='can_manage_permissions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permissiongroup',
            name='can_view_backlog',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='permissiongroup',
            name='can_view_chat',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='permissiongroup',
            name='can_view_docs',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='permissiongroup',
            name='can_view_evaluations',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permissiongroup',
            name='can_view_members',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='permissiongroup',
            name='can_view_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='permissiongroup',
            name='can_view_performance',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='permissiongroup',
            name='can_view_reports',
            field=models.BooleanField(default=True),
        ),
    ]
